Revert "seps: Reduce recovery image size"
error: +out/target/product/spes/boot.img too large (68521984 > 67039232).

This reverts commit 5dbaa3e71af562f51b1d811deb247bbb2f9f3a5f.